name: Prevent Non-Develop PRs to Main

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is not from develop
        run: |
          echo "Checking source branch: ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "❌ Pull requests to main must come from develop branch."
            exit 1
          fi
